# Generated by Django 5.0.6 on 2024-05-13 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
