# Generated by Django 5.0.6 on 2024-05-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargos', models.ManyToManyField(to='nomina.cargonombre')),
            ],
        ),
    ]
