# Generated by Django 5.0.6 on 2024-05-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_cargonombre_cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
