# Generated by Django 5.0.6 on 2024-05-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_rename_important_task_empleado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='CargoNombre',
        ),
    ]
